name: Deploy to Raspberry Pi

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull recent changes
        run: |
          cd $HOME/personal-dashboard
          git pull

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: run elm-live
        run: |
          cd $HOME/personal-dashboard
          http-server