name: Deploy to Raspberry Pi

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Install and setup elm
        run: |
          cd $HOME/elm
          curl -L -o elm.gz https://github.com/elm/compiler/releases/download/0.19.1/binary-for-linux-64-bit.gz
          gunzip elm.gz
          chmod +x elm
          sudo mv elm /usr/local/bin/
          npm install elm-live

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Kill elm-live
        run: pkill elm-live || true

      - name: run elm-live
        run: ./run.sh