name: Update Raspberry Pi

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Pull recent changes and build
        run: |
          cd $HOME/personal-dashboard
          git stash
          git stash clear
          git pull
          cd backend
          go install
          go build main.go

  deploy:
    runs-on: self-hosted
    needs: build
    steps:
      - name: Restart server
        run: sudo systemctl restart go_backend.service